rails/friendbook/config/routes.rb
Rails.application.routes.draw do


  get "accept_request/:id" => "friendships#accept_request", as: :accept_request
  get "delete_request/:id" => "friendships#delete_request", as: :delete_request
  get "pending_request"  => "friendships#index"
  post "add_friend/:id" => "friendships#create", as: :add_friend
  get "remove_friend/:id" => "friendships#destroy", as: :remove_friend
  resources :friendships
  get "users/sign_up" => "users#new", as: :sign_up
  resource :sessions,only:[:new,:create,:destroy]
  resources :users
  root "sessions#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/friendbook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/friendbook/app/models/friendship.rb
class Friendship < ApplicationRecord
  enum status: [:accept, :unaccept,:pending]
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

rails/friendbook/app/models/session.rb
class Session < ApplicationRecord
end

rails/friendbook/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :friendships, dependent: :destroy
  has_many :friend, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  validates :email, presence: true,
              format:{:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i},
              uniqueness: true
end

rails/friendbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def required_signin
     unless current_user
      flash[:error] = "You need to loged in first!!!!"
      redirect_to new_sessions_path
    end
  end



  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

rails/friendbook/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
     @inverse_friendship = current_user.inverse_friendships.pending.map{|fr| fr.user}
  end

  def accept_request
    user = User.find(params[:id])
    friendship = current_user.inverse_friendships.find_by(user_id:user.id)
    friendship.update(status:0)
    flash[:notice] = "You added #{user.name} as a friend!!!"
    redirect_to pending_request_path
  end


  def delete_request
    @user = User.find(params[:id])
    friendship = current_user.inverse_friendships.pending.find_by(user_id:@user.id)
    friendship.destroy
    flash[:error] = "friend request deleted !!!!"
    redirect_to pending_request_path
  end


  def create
    friend = Friendship.new
    friend.user_id = current_user.id
    @friend_to_be_add = User.find(params[:id])
    friend.friend_id = @friend_to_be_add.id
    friend.save
    flash[:notice] = "You sent a friendRequest to #{@friend_to_be_add.name } !!"
    redirect_to users_path
  end

  def destroy
    friends = current_user.friend
    inverse_friends = current_user.inverse_friends
    @friend_to_be_unfriend = User.find(params[:id])
    if friends.map(&:id).include?(@friend_to_be_unfriend.id)
      friends.delete(@friend_to_be_unfriend.id)
    else
      inverse_friends.delete(@friend_to_be_unfriend.id)
    end
    flash[:error] = "you Removed #{@friend_to_be_unfriend.name} from your friend list!!!"
    redirect_to users_path
  end
end

rails/friendbook/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :user_logged_in?,only:[:new]

  def new

  end
  def create
    @email = params[:email]
    @password = params[:password]
    @user = User.find_by(email:@email)
    if @user && @user.authenticate(@password)
      session[:user_id] = @user.id
      if session[:intended_path]
        redirect_to session[:intended_path]
      else
        redirect_to @user
      end
    else
      flash.now[:error] = "invalid email/password"
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    session[:intended_path] = nil
    flash[:notice] = "loged out successfully"
    redirect_to new_sessions_path
  end

  private
  def user_logged_in?
     if current_user
       redirect_to user_path(current_user)
     else
      render :new
    end
  end

end

rails/friendbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if current_user
      @inverse_friendship = current_user.inverse_friendships.accept.map{|fr| fr.user}
    end
    if current_user
      @friendship = current_user.friendships.accept.map{|fr| fr.friend}
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      session[:user_id] = nil
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

rails/friendbook/app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user == user
  end

  def button_for_action(user)
  if current_user

     friendship = Friendship.where("(user_id = :user_id AND friend_id = :friend_id) || (user_id = :friend_id AND friend_id = :user_id)", user_id: user.id, friend_id: current_user.id).first

     if friendship
       case friendship.status
       when 'pending'
          link_to "cancel request" ,remove_friend_path(user), :class => 'btn btn-default btn-xs btn-warning'
       when 'accept'
         link_to "UnFriend" ,remove_friend_path(user), :class => 'btn btn-default btn-xs btn-danger'
       end
     else
       button_to "Add Friend" ,add_friend_path(user), :class => 'btn btn-default btn-xs btn-primary'
     end
   end
 end









  # def already_friend?(user)
  #   current_user.friendships.accept.map(&:friend_id).include?(user.id)
  # end

  # def inverse_friends?(user)
  #   current_user.inverse_friendships.accept.map(&:user_id).include?(user.id)
  # end

  # def friend_pending?(user)
  #   current_user.friendships.pending.map(&:friend_id).include?(user.id)
  # end

  # def inverse_friend_pending?(user)
  #   current_user.inverse_friendships.pending.map(&:user_id).include?(user.id)
  # end
end

rails/friendbook/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

rails/friendbook/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/friendbook/app/helpers/users_helper.rb
module UsersHelper
end

rails/friendbook/app/views/friendships/index.html.erb
<%- model_class = Friendship -%>
<div class="page-header">
  <h1>Pending request</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%  @inverse_friendship.each do |friend| %>
      <tr>
         <td><%= friend.name %></td>
        <td>
        <%=link_to "Accept" ,accept_request_path(friend),:class => 'btn btn-default btn-xs btn-primary' %>
        <%=link_to "Remove" ,delete_request_path(friend),:class => 'btn btn-default btn-xs btn-danger' %>
        </td>
    <%end%>
      </tr>

</table>

rails/friendbook/app/views/shared/_footer.html.erb
<footer class = "footer">
  <div class="footer_content">
    <p>&copy; Company 2019</p>
  </div>
</footer>

rails/friendbook/app/views/shared/_header.html.erb
_<div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FriendBook</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path  %></li>
            <%if current_user %>
             <li><%= link_to "All users", users_path  %></li>
             <li><%= link_to "Request",pending_request_path%>
            <%end%>

          </ul>
          <ul class="nav navbar-nav" style="float: right">
            <% if current_user %>
              <li><%=link_to "#{current_user.name}", user_path(current_user)%>
              <li><%= link_to "Account-Setting",edit_user_path(current_user)%>
              <li><%=link_to "Log out",sessions_path,method: :delete%>
            <%else%>
              <li><%=link_to "Sign Up",new_user_path %>
              <li><%=link_to "Sign in",new_sessions_path%>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

     <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>

rails/friendbook/app/views/shared/_sidebar.html.erb
<div class="col-lg-3">
 <div class="well sidebar-nav">
   <ul class="nav nav-list">
     <li class="nav-header"></li>
     <%=content_for :sidebar%>
   </ul>
</div>

rails/friendbook/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
   <div class="form-group">
    <%= f.label :confirm_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password_confirmation) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

rails/friendbook/app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/friendbook/app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%unless current_user?(user)%>
         <td><%= user.name %></td>
         <td><%= user.email %></td>
        <td>
        <%=button_for_action(user)%>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

rails/friendbook/app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

rails/friendbook/app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>

  <%content_for :sidebar do %>
      <h3>Friends</h3>
      <ul>
      <%if current_user%>
        <%@inverse_friendship.each do |friend|%>
          <li><%=link_to friend.name , user_path(friend)%></li>
        <%end%>
        <% @friendship.each do |friend|%>
          <li><%=link_to friend.name , user_path(friend)%></li>
        <%end%>
        </ul>
      <%end%>
  <%end%>
</dl>




<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>